name: PHP Compatibility
on:
  push

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    strategy:
      matrix:
        php_version: [7.4, 8.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: ${{ matrix.php_version }}-
